name: Sync to Customer Repo
 
on:
  push:
    branches:
      - main
 
jobs:
  mirror:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
        persist-credentials: false   # ✅ CRITICAL FIX
 
    - name: Configure Git
      run: |
        git config --global user.name "revendh"
        git config --global user.email "revendh@users.noreply.github.com"
 
    - name: Push to customer repo
      env:
        TOKEN: ${{ secrets.TARGET_PAT }}
      run: |
        git push https://x-access-token:$TOKEN@github.com/revendh/cust_test.git main
 
